/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RedditPoC.Api
 * OpenAPI spec version: 1.0
 */
export type GetApiV1UsersParams = {
  email: string;
};

export interface User {
  displayName?: string;
  email?: string;
  id?: string;
  username?: string;
}

export interface Error {
  field?: string;
  message?: string;
}

export interface UserResult {
  data?: User;
  errors?: Error[];
  readonly isSuccess?: boolean;
}

export interface Result {
  errors?: Error[];
  readonly isSuccess?: boolean;
}

export interface Command {
  email?: string;
  id?: string;
}
