/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RedditPoC.Api
 * OpenAPI spec version: 1.0
 */
export interface Void {
  [key: string]: unknown;
}

export interface Command {
  email?: string;
  id?: string;
  password?: string;
  username?: string;
}
